blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_entries, name='all_entries'),
    path('<int:entry_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Entry(models.Model):
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=2500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    commenter = models.CharField(max_length=40)
    text = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    parent_entry = models.ForeignKey(Entry, on_delete=models.CASCADE)

class Answer(models.Model):
    commenter = models.CharField(max_length=40)
    text = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Entry, Comment, Answer

def all_entries(request):
    entries = Entry.objects.order_by('-created_at')
    return render(request, 'blog/all_entries.html', {'entries':entries})

def detail(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    comments = Comment.objects.filter(parent_entry=entry_id)
    print("COMMENTS:\n")
    for comment in comments:
        print(comment)
    return render(request, 'blog/detail.html', {
        'entry':entry,
        'comments': comments
        })

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_entries.html
{% extends 'portfolio/base.html'%}
{% block content %}
{% load static %}

<h2>There are {{ entries.count }} blog post{{ entries.count|pluralize }}</h2>
<div class="row">
{% for entry in entries %}
    <div class="col-sm-6">
        <div class="card mb-3">
        <div class="card-body">
            <h4 class="card-title">{{ entry.title }}</h4>
            <p class="card-text">{{ entry.description|striptags|truncatechars:100 }}</p>
            <p class="card-text"><small class="text-muted">{{ entry.created_at|date:'M d Y'|upper }}</small></p>
            <a href="{%  url 'blog:detail' entry.id %}" class="btn btn-primary">Read more...</a>
        </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html'%}
{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">


            <!-- Title -->
            <h1 class="mt-4">{{ entry.title }}</h1>

            {% if entry.author %}
                <!-- Author -->
                <p class="lead">
                by
                <a href="#">Start Bootstrap</a>
                </p>
            {% endif %}

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{ entry.created_at|date:'F jS Y' }}</p>

            <hr>

            {% if entry.image %}
                <!-- Preview Image -->
                <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
                <hr>
            {% endif %}

            <!-- Post Content -->
            {{ entry.description|safe }}

            <hr>

            <!-- Comments Form -->
            <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                <form>
                <div class="form-group">
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            </div>

            {% for comment in comments %}
                <!-- Single Comment -->
                <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{ comment.commenter }}</h5>
                   {{ comment.text|linebreaks }}
                </div>
                </div>
            {% empty %}
                <p>No comments here yet :(</p>
            {% endfor %}

            <!-- Comment with nested comments
            <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

                <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
                </div>

                <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">Commenter Name</h5>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
                </div>

            </div>
            </div>
            -->

        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/vector-logo.svg' %}">

    <title>JaiFab</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg main-nav mb-4">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'portfolio/vector-logo.svg' %}" width=60 height=80>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="icon-bar icon-bar-1"></span>
                            <span class="icon-bar icon-bar-2"></span>
                            <span class="icon-bar icon-bar-3"></span>
                        </button>
            <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto text-uppercase f1">
                <li class="nav-item my-auto active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item my-auto">
                    <a class="nav-link" href="{% url 'blog:all_entries' %}">Blog</a>
                </li>
                <li class="nav-item my-auto">
                    <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}" target="_blank">Resume</a>
                </li>
                <li class="nav-item my-auto">
                    <a class="nav-link" href="https://github.com/jfvalenzuelas" target="_blank"><img src="{% static 'portfolio/path2.png' %}" width="20" height="20"></a>
                </li>
                <li class="nav-item my-auto">
                    <a class="nav-link" href="https://www.linkedin.com/in/jaimefvs/" target="_blank"><img src="{% static 'portfolio/LI-In-Bug.png' %}" width="25" height="20"></a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html'%}
{% block content %}

{% load static %}

<hr>
<div class="row mb-4 align-item-stretch">
    <div class="col col-md-3 mx-auto my-auto">
        <img src="{% static 'portfolio/profile-picture.jpg' %}" class="d-flex mx-auto image-profile" width=150 height=200>
    </div>
    <div class="col-lg-9 col-md-9 mx-auto my-auto">
        <p>Hi! It's nice to have you here!</p><br>
        <p>I wanted to share some Apps and interesting stuff with you.</p><br>
        <p>You can also have access to my Blog and read some of my thoughts.</p>
    </div>
</div>
<hr>
<div class="row justify-content-center">
    <div class="col-lg-12 d-flex align-items-stretch mb-4 justify-content-center">
        <h2 class="text-center">Personal Projects</h2>
    </div>
</div>

<div class="row">
    <div class="col-12">
        {% if projects %}
            {% for project in projects %}
                <div class="card border-0 mb-4">
                    <div class="row">
                        <div class="col-sm-3">
                            <img class="d-block w-100 h-100" src="{{ project.image.url }}" alt="">
                        </div>
                        <div class="col-sm-9">
                            <div class="card-body">
                                <h3> {{ project.title }} </h3>
                                <p> {{ project.description|striptags|truncatechars:140 }} </p>
                                <a href="{{ project.url }}" target="_blank">
                                    <button class="btn btn-primary btn-primary-custom">Explore</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            There are no Projects! What is happening here?!
        {% endif %}
    </div>
</div>
<hr>

{% endblock %}